---
# There was an upstream change to upper case file names
- name: Delete former DMARC plugin files
  file:
    path: "/etc/spamassassin/{{ item }}"
    state: absent
  with_items:
    - Dmarc.pm
    - Dmarc.cf
    - Dmarc.pre

- name: Enable DMARC plugin
  when: spamassassin_dmarc_enabled
  block:
    - name: Install DMARC dependencies
      apt:
        name: "{{ spamassassin_dmarc_dependencies }}"
        state: present
      register: dmarc_install

    - name: Install DMARC build dependencies
      apt:
        name: "{{ spamassassin_dmarc_dependencies_build }}"
      notify: Remove build dependencies
      when: dmarc_install.changed

    - name: Install perl modules
      community.general.cpanm:
        name: "{{ item }}"
        notest: true
      with_items:
        - "IO::Compress::Zstd"
        - "Mail::DMARC::PurePerl"
      when: dmarc_install.changed
      notify: Restart spamassassin

    - name: Get DMARC plugin files
      get_url:
        url: "https://github.com/bigio/spamassassin-dmarc/raw/master/{{ item }}"
        dest: /etc/spamassassin/
        mode: '0644'
      with_items:
        - DMARC.pm
        - DMARC.cf
        - DMARC.pre
      notify: Restart spamassassin

- name: Delete DMARC plugin
  file:
    path: "/etc/spamassassin/{{ item }}"
    state: absent
  with_items:
    - DMARC.pm
    - DMARC.cf
    - DMARC.pre
  when: not spamassassin_dmarc_enabled
  notify: Restart spamassassin
