---

- name: ensure spamassassin is installed
  apt:
    pkg: "{{ spamassassin_packages }}"
    state: present

- block:
    - name: ensure spamd group is present
      group:
        name: "{{ spamassassin_user }}"
        state: present

    - name: ensure spamd user is present
      user:
        name: "{{ spamassassin_user }}"
        shell: /bin/sh
        home: "{{ spamassassin_home_dir }}"
        group: "{{ spamassassin_group }}"

    - name: ensure spamassassin's directories are present
      file:
        path: "{{ item }}"
        owner: "{{ spamassassin_user }}"
        group: "{{ spamassassin_user }}"
        mode: 0755
        state: directory
      with_items:
        - "{{ spamassassin_home_dir }}"
        - "{{ spamassassin_bayes_path }}"

    - name: ensure spamassassin config is latest
      template:
        src: default/spamassassin.j2
        dest: /etc/default/spamassassin
        owner: root
        group: root
        mode: 0644
      notify: restart spamassassin

    - name: ensure spamassassin default rules file is latest
      template:
        src: spamassassin/local.cf.j2
        dest: /etc/spamassassin/local.cf
        owner: root
        group: root
        mode: 0644
      notify: restart spamassassin

    - name: ensure spamassassin whitelist is latest
      template:
        src: spamassassin/whitelist.cf.j2
        dest: /etc/spamassassin/whitelist.cf
        owner: root
        group: root
        mode: 0644
      notify:
        - reload spamassassin

    - name: ensure spamassassin logrotate is latest
      template:
        src: logrotate.d/spamd.j2
        dest: /etc/logrotate.d/spamd
        owner: root
        group: root
        mode: 0644
  when: spamassassin_configure

- name: ensure spamassassin ruleupdate cronjob is latest
  template:
    src: cron.daily/spamassassin.j2
    dest: /etc/cron.daily/spamassassin
    owner: root
    group: root
    mode: 0755
  notify: restart spamassassin

- name: ensure cronjob for spamtraining is present
  cron:
    name: "Spamassassin enable spamtraining for {{ item[1] }}@{{ item[0].domain }}"
    minute: "0"
    hour: "0"
    job: "/usr/bin/sa-learn --dbpath {{ spamassassin_bayes_path }}/ --progress \
 --spam /var/vmail/{{ item[0].domain }}/{{ item[1] }}/Maildir/.Junk > /dev/null 2>&1"
  with_subelements:
    - "{{ spamassassin_spamtraining_users }}"
    - users

- name: ensure spamassassin is enabled and started
  service:
    name: spamassassin
    enabled: True
    state: started

- include: pyzor.yml
  when: spamassassin_pyzor_enabled

- include: razor.yml
  when: spamassassin_razor_enabled

- include: monit.yml
  when: spamassassin_monit_enabled
