---
- name: Ensure spamassassin packages are installed
  apt:
    pkg: "{{ spamassassin_packages }}"
    state: present
    cache_valid_time: 600

- name: Basic configuration
  when: spamassassin_configure
  block:
    - name: Ensure spamd group is present
      group:
        name: "{{ spamassassin_user }}"
        state: present

    - name: Ensure spamd user is present
      user:
        name: "{{ spamassassin_user }}"
        shell: /bin/sh
        home: "{{ spamassassin_home_dir }}"
        group: "{{ spamassassin_group }}"

    - name: Ensure spamassassin's directories are present
      file:
        path: "{{ item }}"
        owner: "{{ spamassassin_user }}"
        group: "{{ spamassassin_user }}"
        mode: 0755
        state: directory
      with_items:
        - "{{ spamassassin_home_dir }}"
        - "{{ spamassassin_bayes_path }}"

    - name: Ensure spamassassin config is latest
      template:
        src: default/spamassassin.j2
        dest: /etc/default/spamassassin
        owner: root
        group: root
        mode: 0644
      notify: Restart spamd

    - name: Ensure spamassassin default rules file is latest
      template:
        src: spamassassin/local.cf.j2
        dest: /etc/spamassassin/local.cf
        owner: root
        group: root
        mode: 0644
      notify: Restart spamd

    - name: Ensure spamassassin welcomelist is latest
      template:
        src: spamassassin/welcomelist.cf.j2
        dest: "/etc/spamassassin/welcomelist.cf"
        owner: root
        group: root
        mode: 0644
      notify: Reload spamd

    - name: Ensure spamassassin logrotate is latest
      template:
        src: logrotate.d/spamd.j2
        dest: /etc/logrotate.d/spamd
        owner: root
        group: root
        mode: 0644

- name: Ensure spamassassin ruleupdate maintenance script is latest
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - { src: 'spamassassin/spamassassin-maint.j2', dest: '/usr/sbin/spamassassin-maint'}

- name: Ensure cronjob for spamtraining is present
  cron:
    name: "Spamassassin enable spamtraining for {{ item[1] }}@{{ item[0].domain }}"
    minute: "0"
    hour: "0"
    job: "/usr/bin/sa-learn --dbpath {{ spamassassin_bayes_path }}/ --progress \
      --spam /var/vmail/{{ item[0].domain }}/{{ item[1] }}/Maildir/.Junk > /dev/null 2>&1"
  with_subelements:
    - "{{ spamassassin_spamtraining_users }}"
    - users

- name: Ensure spamassassin daemon is enabled and started
  service:
    name: spamd
    enabled: True
    state: started

- name: Ensure systemd timer for maintenance script is enabled
  service:
    name: spamassassin-maintenance.timer
    enabled: True
    state: started

- name: Import pyzor tasks
  import_tasks: pyzor.yml
  when: spamassassin_pyzor_enabled

- name: Import razor tasks
  import_tasks: razor.yml
  when: spamassassin_razor_enabled

- name: Import mtail tasks
  import_tasks: mtail.yml
  when: spamassassin_mtail_enabled
