---
- name: Check if pyzor is already installed
  ansible.builtin.stat:
    path: /usr/bin/pyzor
  register: pyzor_installed

- name: Ensure pyzor is installed
  ansible.builtin.apt:
    pkg: pyzor
    state: present

- name: Ensure pyzor discovered mail configuration after install
  ansible.builtin.command: pyzor --homedir {{ spamassassin_pyzor_config_dir }} discover
  args:
    creates: "{{ spamassassin_pyzor_config_dir }}/servers"
  when: not pyzor_installed.stat.exists
  notify: Restart spamd
