---
- name: Lint configs to catch errors
  ansible.builtin.command: /usr/bin/spamassassin --lint
  changed_when: True
  listen: "Restart spamd"

- name: Restart spamd
  ansible.builtin.service:
    name: spamd
    state: restarted
  listen: "Restart spamd"
