---
- name: Restart spamassassin
  service:
    name: spamassassin
    state: restarted

- name: Reload spamassassin
  service:
    name: spamassassin
    state: reloaded

- name: Restart monit
  service:
    name: monit
    state: restarted

- name: Remove build dependencies
  apt:
    name: "{{ spamassassin_dmarc_dependencies_build }}"
    state: absent
