---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: spamassassin-bullseye64
    box: debian/bullseye64
  - name: spamassassin-buster64
    box: debian/buster64
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  become: true
