---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: stretch64
    box: debian/stretch64
    memory: 512
    cpus: 1
  - name: jessie64
    box: debian/jessie64
    memory: 512
    cpus: 1
lint: yamllint .
provisioner:
  name: ansible
  options:
    vvv: True
  become: true
  log: True
