---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: spamassassin-bullseye64
    box: debian/bullseye64
  - name: spamassassin-bookworm64
    box: debian/bookworm64

provisioner:
  name: ansible
  ansible_args:
    - --diff
  become: true
