---
- name: Prepare backports for Bullseye
  hosts: spamassassin-bullseye64-backports
  become: True
  tasks:
    - name: Add backports repository
      ansible.builtin.apt_repository:
        repo: deb http://deb.debian.org/debian bullseye-backports main
        state: present
    - name: Pin spamassassin package
      copy:
        dest: /etc/apt/preferences.d/99bullseye-backports
        content: |
               Package: spamassassin
               Pin: release a=bullseye-backports
               Pin-Priority: 900

- name: Prepare
  hosts: all
  become: True
  tasks:
    - name: Run the equivalent of "apt-get update" before installing packages
      apt:
        update_cache: yes

    - name: Install cron for testing in docker containers
      apt:
        pkg: cron
        update_cache: yes
