---
- name: Prepare
  hosts: all
  become: True
  tasks:
    - name: Run the equivalent of "apt-get update" before installing packages
      apt:
        update_cache: yes

    - name: Install cron for testing in docker containers
      apt:
        pkg: cron
        update_cache: yes
